api_platform:
    mapping:
        paths:
            [
                "%kernel.project_dir%/vendor/controleonline/common/src/Entity",
                "%kernel.project_dir%/vendor/controleonline/common/src/Resource",
            ]
    
